import { defineShortcuts } from '@/content/define';

export const essentials = defineShortcuts('win11', 'essentials', [
  {
    slug: 'ctrl-c',
    keys: 'Ctrl+C',
    difficulty: 1,
    capturable: 'full',
    en: { name: 'Copy', description: 'Copy the selected item to the clipboard.' },
    ar: { name: 'نسخ', description: 'انسخ العنصر المحدد إلى الحافظة.' },
  },
  {
    slug: 'ctrl-x',
    keys: 'Ctrl+X',
    difficulty: 1,
    capturable: 'full',
    en: { name: 'Cut', description: 'Cut the selected item to the clipboard.' },
    ar: { name: 'قص', description: 'قص العنصر المحدد إلى الحافظة.' },
  },
  {
    slug: 'ctrl-v',
    keys: 'Ctrl+V',
    difficulty: 1,
    capturable: 'full',
    en: { name: 'Paste', description: 'Paste the clipboard contents.' },
    ar: { name: 'لصق', description: 'الصق محتوى الحافظة.' },
  },
  {
    slug: 'ctrl-z',
    keys: 'Ctrl+Z',
    difficulty: 1,
    capturable: 'full',
    en: { name: 'Undo', description: 'Undo the last action.' },
    ar: { name: 'تراجع', description: 'تراجع عن آخر إجراء.' },
  },
  {
    slug: 'ctrl-y',
    keys: 'Ctrl+Y',
    difficulty: 2,
    capturable: 'full',
    en: { name: 'Redo', description: 'Redo the last undone action.' },
    ar: { name: 'إعادة', description: 'أعد تنفيذ آخر إجراء تراجعت عنه.' },
  },
  {
    slug: 'ctrl-a',
    keys: 'Ctrl+A',
    difficulty: 1,
    capturable: 'full',
    en: { name: 'Select all', description: 'Select every item in the current view.' },
    ar: { name: 'تحديد الكل', description: 'حدد كل العناصر في العرض الحالي.' },
  },
  {
    slug: 'ctrl-f',
    keys: 'Ctrl+F',
    difficulty: 1,
    capturable: 'full',
    en: { name: 'Find', description: 'Open search within the current document or app.' },
    ar: { name: 'بحث', description: 'افتح البحث داخل المستند أو التطبيق الحالي.' },
  },
  {
    slug: 'ctrl-s',
    keys: 'Ctrl+S',
    difficulty: 1,
    capturable: 'full',
    en: { name: 'Save', description: 'Save the current document.' },
    ar: { name: 'حفظ', description: 'احفظ المستند الحالي.' },
  },
  {
    slug: 'f2',
    keys: 'F2',
    difficulty: 2,
    capturable: 'full',
    en: { name: 'Rename', description: 'Rename the selected file or folder.' },
    ar: { name: 'إعادة تسمية', description: 'أعد تسمية الملف أو المجلد المحدد.' },
  },
  {
    slug: 'shift-f10',
    keys: 'Shift+F10',
    difficulty: 3,
    capturable: 'partial',
    en: { name: 'Context menu', description: 'Open the right-click menu for the selection.' },
    ar: { name: 'قائمة السياق', description: 'افتح قائمة النقر الأيمن للعنصر المحدد.' },
  },
  {
    slug: 'esc',
    keys: 'Esc',
    difficulty: 1,
    capturable: 'full',
    en: { name: 'Cancel', description: 'Dismiss the current dialog or cancel the action.' },
    ar: { name: 'إلغاء', description: 'أغلق مربع الحوار الحالي أو ألغِ الإجراء.' },
  },
]);
