import { defineShortcuts } from '@/content/define';

export const fileExplorer = defineShortcuts('win11', 'file-explorer', [
  {
    slug: 'ctrl-n',
    keys: 'Ctrl+N',
    difficulty: 2,
    capturable: 'none',
    en: { name: 'New window', description: 'Open a new File Explorer window.' },
    ar: { name: 'نافذة جديدة', description: 'افتح نافذة جديدة في مستكشف الملفات.' },
  },
  {
    slug: 'ctrl-w',
    keys: 'Ctrl+W',
    difficulty: 2,
    capturable: 'none',
    en: { name: 'Close window', description: 'Close the current File Explorer window.' },
    ar: { name: 'إغلاق النافذة', description: 'أغلق نافذة مستكشف الملفات الحالية.' },
  },
  {
    slug: 'ctrl-shift-n',
    keys: 'Ctrl+Shift+N',
    difficulty: 2,
    capturable: 'none',
    en: { name: 'New folder', description: 'Create a new folder.' },
    ar: { name: 'مجلد جديد', description: 'أنشئ مجلدًا جديدًا.' },
  },
  {
    slug: 'alt-up',
    keys: 'Alt+Up',
    difficulty: 2,
    capturable: 'full',
    en: { name: 'Up one level', description: 'Go to the parent folder.' },
    ar: { name: 'مستوى أعلى', description: 'انتقل إلى المجلد الأب.' },
  },
  {
    slug: 'alt-left',
    keys: 'Alt+Left',
    difficulty: 2,
    capturable: 'partial',
    en: { name: 'Back', description: 'Go back to the previous folder.' },
    ar: { name: 'رجوع', description: 'ارجع إلى المجلد السابق.' },
  },
  {
    slug: 'alt-right',
    keys: 'Alt+Right',
    difficulty: 2,
    capturable: 'partial',
    en: { name: 'Forward', description: 'Go forward to the next folder.' },
    ar: { name: 'تقدّم', description: 'تقدّم إلى المجلد التالي.' },
  },
  {
    slug: 'ctrl-l',
    keys: 'Ctrl+L',
    difficulty: 3,
    capturable: 'none',
    en: { name: 'Address bar', description: 'Focus the address bar to type a path.' },
    ar: { name: 'شريط العنوان', description: 'انتقل إلى شريط العنوان لكتابة مسار.' },
  },
  {
    slug: 'ctrl-e',
    keys: 'Ctrl+E',
    difficulty: 3,
    capturable: 'full',
    en: { name: 'Search box', description: 'Focus the search box in File Explorer.' },
    ar: { name: 'مربع البحث', description: 'انتقل إلى مربع البحث في مستكشف الملفات.' },
  },
  {
    slug: 'alt-enter',
    keys: 'Alt+Enter',
    difficulty: 3,
    capturable: 'full',
    en: { name: 'Properties', description: 'Open Properties for the selected item.' },
    ar: { name: 'الخصائص', description: 'افتح خصائص العنصر المحدد.' },
  },
  {
    slug: 'f11',
    keys: 'F11',
    difficulty: 3,
    capturable: 'partial',
    en: { name: 'Full screen', description: 'Toggle full-screen mode.' },
    ar: { name: 'ملء الشاشة', description: 'بدّل وضع ملء الشاشة.' },
  },
]);
