import { defineShortcuts } from '@/content/define';

export const windowManagement = defineShortcuts('win11', 'window-management', [
  {
    slug: 'alt-tab',
    keys: 'Alt+Tab',
    difficulty: 1,
    capturable: 'none',
    en: { name: 'Switch apps', description: 'Switch between open apps.' },
    ar: { name: 'التبديل بين التطبيقات', description: 'بدّل بين التطبيقات المفتوحة.' },
  },
  {
    slug: 'win-tab',
    keys: 'Win+Tab',
    difficulty: 2,
    capturable: 'none',
    en: { name: 'Task View', description: 'Open Task View with all windows and desktops.' },
    ar: { name: 'عرض المهام', description: 'افتح عرض المهام بكل النوافذ وأسطح المكتب.' },
  },
  {
    slug: 'alt-f4',
    keys: 'Alt+F4',
    difficulty: 2,
    capturable: 'none',
    en: { name: 'Close app', description: 'Close the active window or app.' },
    ar: { name: 'إغلاق التطبيق', description: 'أغلق النافذة أو التطبيق النشط.' },
  },
  {
    slug: 'win-up',
    keys: 'Win+Up',
    difficulty: 2,
    capturable: 'partial',
    en: { name: 'Maximize window', description: 'Maximize the active window.' },
    ar: { name: 'تكبير النافذة', description: 'كبّر النافذة النشطة.' },
  },
  {
    slug: 'win-down',
    keys: 'Win+Down',
    difficulty: 2,
    capturable: 'partial',
    en: { name: 'Minimize window', description: 'Restore or minimize the active window.' },
    ar: { name: 'تصغير النافذة', description: 'استعد النافذة النشطة أو صغّرها.' },
  },
  {
    slug: 'win-left',
    keys: 'Win+Left',
    difficulty: 2,
    capturable: 'partial',
    en: { name: 'Snap left', description: 'Snap the active window to the left half.' },
    ar: { name: 'التثبيت لليسار', description: 'ثبّت النافذة النشطة في النصف الأيسر.' },
  },
  {
    slug: 'win-right',
    keys: 'Win+Right',
    difficulty: 2,
    capturable: 'partial',
    en: { name: 'Snap right', description: 'Snap the active window to the right half.' },
    ar: { name: 'التثبيت لليمين', description: 'ثبّت النافذة النشطة في النصف الأيمن.' },
  },
  {
    slug: 'win-z',
    keys: 'Win+Z',
    difficulty: 3,
    capturable: 'partial',
    en: { name: 'Snap layouts', description: 'Open snap layouts for the active window.' },
    ar: { name: 'تخطيطات التثبيت', description: 'افتح تخطيطات التثبيت للنافذة النشطة.' },
  },
  {
    slug: 'win-home',
    keys: 'Win+Home',
    difficulty: 3,
    capturable: 'partial',
    en: { name: 'Minimize others', description: 'Minimize all windows except the active one.' },
    ar: { name: 'تصغير النوافذ الأخرى', description: 'صغّر كل النوافذ ما عدا النشطة.' },
  },
  {
    slug: 'win-m',
    keys: 'Win+M',
    difficulty: 2,
    capturable: 'partial',
    en: { name: 'Minimize all', description: 'Minimize all open windows.' },
    ar: { name: 'تصغير الكل', description: 'صغّر كل النوافذ المفتوحة.' },
  },
  {
    slug: 'win-shift-m',
    keys: 'Win+Shift+M',
    difficulty: 3,
    capturable: 'partial',
    en: { name: 'Restore minimized', description: 'Restore windows minimized with Win+M.' },
    ar: { name: 'استعادة المصغّرة', description: 'استعد النوافذ التي صُغّرت بـ Win+M.' },
  },
  {
    slug: 'alt-esc',
    keys: 'Alt+Esc',
    difficulty: 4,
    capturable: 'none',
    en: { name: 'Cycle windows', description: 'Cycle through windows in the order they were opened.' },
    ar: { name: 'التنقل بين النوافذ', description: 'تنقّل بين النوافذ بترتيب فتحها.' },
  },
]);
