import { defineShortcuts } from '@/content/define';

export const windowsKey = defineShortcuts('win11', 'windows-key', [
  {
    slug: 'win-e',
    keys: 'Win+E',
    difficulty: 1,
    capturable: 'partial',
    en: { name: 'File Explorer', description: 'Open File Explorer.' },
    ar: { name: 'مستكشف الملفات', description: 'افتح مستكشف الملفات.' },
  },
  {
    slug: 'win-i',
    keys: 'Win+I',
    difficulty: 1,
    capturable: 'partial',
    en: { name: 'Settings', description: 'Open the Settings app.' },
    ar: { name: 'الإعدادات', description: 'افتح تطبيق الإعدادات.' },
  },
  {
    slug: 'win-s',
    keys: 'Win+S',
    difficulty: 1,
    capturable: 'partial',
    en: { name: 'Search', description: 'Open Windows Search.' },
    ar: { name: 'البحث', description: 'افتح بحث ويندوز.' },
  },
  {
    slug: 'win-d',
    keys: 'Win+D',
    difficulty: 2,
    capturable: 'partial',
    en: { name: 'Show desktop', description: 'Show or hide the desktop.' },
    ar: { name: 'إظهار سطح المكتب', description: 'أظهر سطح المكتب أو أخفه.' },
  },
  {
    slug: 'win-r',
    keys: 'Win+R',
    difficulty: 2,
    capturable: 'partial',
    en: { name: 'Run', description: 'Open the Run dialog.' },
    ar: { name: 'تشغيل', description: 'افتح مربع حوار "تشغيل".' },
  },
  {
    slug: 'win-x',
    keys: 'Win+X',
    difficulty: 3,
    capturable: 'partial',
    en: { name: 'Quick Link menu', description: 'Open the power-user menu (Start button right-click).' },
    ar: { name: 'قائمة الارتباطات السريعة', description: 'افتح قائمة المستخدم المتقدم (النقر الأيمن على زر ابدأ).' },
  },
  {
    slug: 'win-a',
    keys: 'Win+A',
    difficulty: 2,
    capturable: 'partial',
    en: { name: 'Quick Settings', description: 'Open Quick Settings (Wi-Fi, volume, brightness).' },
    ar: { name: 'الإعدادات السريعة', description: 'افتح الإعدادات السريعة (الواي فاي والصوت والسطوع).' },
  },
  {
    slug: 'win-n',
    keys: 'Win+N',
    difficulty: 2,
    capturable: 'partial',
    en: { name: 'Notification center', description: 'Open the notification center and calendar.' },
    ar: { name: 'مركز الإشعارات', description: 'افتح مركز الإشعارات والتقويم.' },
  },
  {
    slug: 'win-v',
    keys: 'Win+V',
    difficulty: 2,
    capturable: 'partial',
    en: { name: 'Clipboard history', description: 'Open clipboard history to paste earlier items.' },
    ar: { name: 'سجل الحافظة', description: 'افتح سجل الحافظة للصق عناصر سابقة.' },
  },
  {
    slug: 'win-p',
    keys: 'Win+P',
    difficulty: 3,
    capturable: 'partial',
    en: { name: 'Project display', description: 'Choose a presentation display mode.' },
    ar: { name: 'عرض الشاشة', description: 'اختر وضع عرض الشاشة الخارجية.' },
  },
  {
    slug: 'win-k',
    keys: 'Win+K',
    difficulty: 3,
    capturable: 'partial',
    en: { name: 'Cast', description: 'Connect to wireless displays and audio devices.' },
    ar: { name: 'البث', description: 'اتصل بشاشات وأجهزة صوت لاسلكية.' },
  },
  {
    slug: 'win-w',
    keys: 'Win+W',
    difficulty: 2,
    capturable: 'partial',
    en: { name: 'Widgets', description: 'Open the widgets panel.' },
    ar: { name: 'الأدوات المصغّرة', description: 'افتح لوحة الأدوات المصغّرة.' },
  },
  {
    slug: 'win-period',
    keys: 'Win+.',
    difficulty: 2,
    capturable: 'partial',
    en: { name: 'Emoji panel', description: 'Open the emoji and symbols picker.' },
    ar: { name: 'لوحة الرموز التعبيرية', description: 'افتح منتقي الرموز التعبيرية والرموز.' },
  },
  {
    slug: 'win-g',
    keys: 'Win+G',
    difficulty: 3,
    capturable: 'partial',
    en: { name: 'Game Bar', description: 'Open the Xbox Game Bar.' },
    ar: { name: 'شريط الألعاب', description: 'افتح شريط ألعاب Xbox.' },
  },
  {
    slug: 'win-h',
    keys: 'Win+H',
    difficulty: 3,
    capturable: 'partial',
    en: { name: 'Voice typing', description: 'Start voice typing.' },
    ar: { name: 'الكتابة الصوتية', description: 'ابدأ الكتابة الصوتية.' },
  },
]);
